---
force_update_check:
  name: Force Update Check
  description: Force an immediate update check for all containers

start_container:
  name: Start Container
  description: Start a Docker container through Portainer. Either use endpoint_id and container_id together or name alone.
  fields:
    endpoint_id:
      description: Portainer endpoint ID
      example: 1
    container_id:
      description: Container ID
      example: "abc123"
    name:
      description: container name.
      example: Homeassistant  
      

stop_container:
  name: Stop Container
  description: Stop a Docker container through Portainer. Either use endpoint_id and container_id together or name alone.
  fields:
    endpoint_id:
      description: Portainer endpoint ID
      example: 1
    container_id:
      description: Container ID
      example: "abc123"

restart_container:
  name: Restart Container
  description: Restart a Docker container through Portainer. Either use endpoint_id and container_id together or name alone.
  fields:
    endpoint_id:
      description: Portainer endpoint ID
      example: 1
    container_id:
      description: Container ID
      example: "abc123"

start_stack:
  name: Start Stack
  description: Start a stack through Portainer (requires Business Edition)
  fields:
    endpoint_id:
      description: Portainer endpoint ID
      example: 1
    stack_id:
      description: Stack ID
      example: 42

stop_stack:
  name: Stop Stack
  description: Stop a stack through Portainer (requires Business Edition)
  fields:
    endpoint_id:
      description: Portainer endpoint ID
      example: 1
    stack_id:
      description: Stack ID
      example: 42
